# Generated by Django 6.0.4 on 2026-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_status_employee_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(max_length=100),
        ),
    ]
